### ISSUE TITLE
Module import error

### ISSUE THREAD

**Issue by wuzhe71** [GestaltCogTeam/STEP#31] opened 2023-02-14 09:28 UTC
Hello, this is a nice work, but I meet some problems when running the code

Input:
> `python step/run.py --cfg='step/TSFormer_PEMS04.py' --gpus='0, 1'`

Output
Exception has occurred: TypeError
the 'package' argument is required to perform a relative import for '.basicts.data.dataset'
  File "E:\code\Traffic\Analysis\STEP\basicts\data\__init__.py", line 10, in <module>
    scan_modules(os.getcwd(), __file__, ["__init__.py", "registry.py"])
  File "E:\code\Traffic\Analysis\STEP\step\step_runner\tsformer_runner.py", line 4, in <module>
    from basicts.data.registry import SCALER_REGISTRY
  File "E:\code\Traffic\Analysis\STEP\step\step_runner\__init__.py", line 1, in <module>
    from .tsformer_runner import TSFormerRunner
  File "E:\code\Traffic\Analysis\STEP\step\TSFormer_PEMS04.py", line 10, in <module>
    from .step_runner import TSFormerRunner
  File "E:\code\Traffic\Analysis\STEP\basicts\launcher.py", line 19, in launch_training
    easytorch.launch_training(cfg=cfg, gpus=gpus, node_rank=node_rank)
  File "E:\code\Traffic\Analysis\STEP\step\run.py", line 26, in <module>
    launch_training(args.cfg, args.gpus)
TypeError: the 'package' argument is required to perform a relative import for '.basicts.data.dataset'

**Comment by zezhishao** [comment] 2023-02-14 12:54
Sorry, I can not reproduce your error.
Can you provide more details?

**Comment by zezhishao** [comment] 2023-02-14 13:03
Sorry, I can't reproduce your error. Running the code from this repo directly seems to work fine.
Can you provide more details? For example, do you have additional modifications to the code, and what are your versions of Python, PyTorch, and EasyTorch?

**Comment by wuzhe71** [comment] 2023-02-15 02:17
@zezhishao 

The packages' version are Python=3.8.12  PyTorch=1.7.1  EasyTorch=1.2.10, and I use VS code to run this project.

When I use `python step/run.py` instead of `python step/run.py --cfg='step/STEP_PEMS04.py' --gpus='0, 1'`, the model can be trained normally. When I use the Debug or Execution mode of the VS code, this problem has occurred. It seems that this problem is caused by the `basicts/data/registry.py` file.

**Comment by zezhishao** [comment] 2023-02-15 02:34
That's strange. I still can't reproduce this error. Here is my setup:
- OS: Ubuntu 22.04
- Python=3.9, PyTorch=1.9.1, EasyTorch=1.2.10
- Just run the code in this repo without any modifications.
- I also use VSCode to run this project.

Then, I tested:
- Run the command line `python step/run.py`,
- Run the command line `python step/run.py --cfg='step/STEP_PEMS04.py' --gpus='0, 1'`,
- Debug mode of the VSCode,
- Execution mode of the VSCode.

They all worked fine.

**Comment by zezhishao** [comment] 2023-02-15 03:39
This is a compatibility issue caused by Windows, I'll fix it later.

**Comment by zezhishao** [comment] 2023-02-15 04:02
You can temporarily fix this issue by modifying `basicts.data.__init__.py`:

```python
import os
import platform

from easytorch.utils.registry import scan_modules

from .registry import SCALER_REGISTRY
from .dataset import TimeSeriesForecastingDataset

__all__ = ["SCALER_REGISTRY", "TimeSeriesForecastingDataset"]

project_dir = os.getcwd()
if platform.system().lower() == 'windows':
    # On Windows systems, os.getcwd() will get an uppercase drive letter, such as C:\\Users\\...
    # However, the drive letter obtained by __file__ is lowercase, such as c:\\Users\\...
    project_dir = project_dir[0].lower() + project_dir[1:]

scan_modules(project_dir, __file__, ["__init__.py", "registry.py"])
```

This issue will be officially fixed in the next EasyTorch version.

**Comment by zezhishao** [comment] 2023-02-16 02:38
Fixed in the latest commit.

**Closed as completed by zezhishao** 2023-02-16 02:38 UTC

**Comment by wuzhe71** [comment] 2023-02-20 07:30
@zezhishao thanks a lot

**Comment by zezhishao** [comment] 2023-02-20 07:55
You're welcome! If you have any questions, please feel free to open a new issue.
